### ISSUE TITLE
Unstable Block Rendering Issues

### ISSUE THREAD

**Issue by WenXin20** [Tfarcenim/Unstable-Tools#2]
`Minecraft v1.14.4`
`Forge v28.1.90`
`Unstable Tools v3.5`

- Provides an X-ray glitch when placed.
- Renders invisible when placed underwater. (Should instead render similarily to Minecraft glass)
- Missing localization

![2019-11-18_22 43 47](https://user-images.githubusercontent.com/12000593/69117896-de398c00-0a56-11ea-97c8-fa5130419633.png)

**Comment by Tfarcenim** [comment]
* xray is intentional
* invisibility has been fixed
* localization has been fixed
