### ISSUE TITLE
[1.12.2] Uses Left goes into negative value for an Division Sigil (activated)

### ISSUE THREAD

**Issue by saovenn** [Tfarcenim/Unstable-Tools#3]
- Mod version: unstabletools-1.3

**Describe the Problem:**
Hello,

We wanted to make custom recipes with the Division Sigil and took an activated Division Sigil (not the stable) and found that the value of "Uses Left" goes into the negative range and therefore the "Uses Left" does not really have a usage like in the 1.7.10 version.

**To Reproduce**

1. Give an Activated Division Sigil (CraftTweaker: `/ct give <unstabletools:division_sign>.withTag({d: 2 as long, activated: 1 as byte}) `)
2. Now craft so many unstable ingots that the value of the positive goes into the negative and doesn't stop at 0

If there is no function for the Division Sigil (Activated) yet, it would be nice if it could be implemented so we could use it in our modpack :)

I made a video of it - if you have any questions just let me know
**[Video](https://saoven.de/xFEIsc0W.mp4)**

**Comment by Tfarcenim** [comment]
fixed in 1.4
