### ISSUE TITLE
[1.19.2] Crash when booting the client.

### ISSUE THREAD

**Issue by Gbergz** [Tfarcenim/Unstable-Tools#4]
Attempting to boot the game with the latest newest version of Unstable tools for 1.19.2 is crashing the client.

**Versions:**
MC: 1.19.2
Forge: 43.2.3
Unstable Tools: 2.7 | https://www.curseforge.com/minecraft/mc-mods/unstable-tools/files/4339325

**Crash-Report:** https://gist.githubusercontent.com/Gbergz/ac5bd0f01a405c74b24aee66056afb46/raw/0b14aea1e20351f057efe5f814a052d328bdf7ba/gistfile1.txt

**Full Logs**:
https://gist.githubusercontent.com/Gbergz/b3ef3188ae72218166ca7bc2015b348e/raw/4a01fea9d7f79bafa276e40a5f0c83f2d85889ab/gistfile1.txt

**Comment by Gbergz** [comment]
Tried new version, it doesn't boot. https://www.curseforge.com/minecraft/mc-mods/unstable-tools/files/4379921

Logs: https://gist.githubusercontent.com/Gbergz/69a60b39fd2773970827a0d7f2c59ab6/raw/48ed226736ff1d9bb1b176173b35a8802c0a97a1/gistfile1.txt

**Comment by Tfarcenim** [comment]
fixed again
