### ISSUE TITLE
[1.18.2] Game crashes on startup

### ISSUE THREAD

**Issue by trkei** [Tfarcenim/Unstable-Tools#6]
Game instantly crashes with exit code 1. Only mod installed is Unstable Tools.

Versions:
MC: 1.18.2
Forge: 40.2.8
Unstable Tools: [1.18.2-6](https://www.curseforge.com/minecraft/mc-mods/unstable-tools/files/4337439)

[latest.log](https://pastebin.com/KUrxXtaf)

**Comment by Tfarcenim** [comment]
fixed in 1.18.2-7
